import { GoogleGenAI } from '@google/genai';
import { ChatMessage, ChatContext } from '../types';

const getApiKey = () => {
    const runtimeEnv = (typeof window !== 'undefined') ? (window as any).env : {};
    return runtimeEnv?.VITE_GEMINI_API_KEY || (import.meta as any).env.VITE_GEMINI_API_KEY;
};

const apiKey = getApiKey();
export const sendChatMessage = async (
    message: string,
    chatHistory: ChatMessage[],
    context: ChatContext
): Promise<string> => {

    if (!apiKey) {
        throw new Error('GEMINI_API_KEY not configured');
    }

    const ai = new GoogleGenAI({ apiKey });

    // Build system context
    const systemContext = buildSystemContext(context);

    // Convert chat history to prompt context
    // USER REQUEST: Disable history to prevent context issues
    const conversationHistory = chatHistory
        .filter(msg => !msg.isStreaming)
        .map(msg => `${msg.role === 'user' ? 'User' : 'Assistant'}: ${msg.content}`)
        .join('\n\n');

    const fullPrompt = `${systemContext}

PREVIOUS CONVERSATION:
${conversationHistory}

USER QUESTION: ${message}

Provide a helpful, concise response as an expert options trading assistant. Use bullet points for clarity when appropriate.`;

    const result = await ai.models.generateContent({
        model: 'gemini-3-pro-preview',
        contents: fullPrompt,
        config: {
            temperature: 0.2,
            // @ts-ignore
            thinking_level: "HIGH"
        }
    });

    const text = result.text || 'Sorry, I could not generate a response.';
    return `${text}\n\n_(Generated by Gemini 3 Pro)_`;
};

function buildSystemContext(context: ChatContext): string {
    return `You are an expert options trading assistant helping a day trader analyze ${context.ticker}.

CURRENT MARKET DATA:
- Ticker: ${context.ticker}
- Current Price: $${context.currentPrice.toFixed(2)}
- Change: ${context.changePercent >= 0 ? '+' : ''}${context.changePercent.toFixed(2)}%

${context.analysis ? `PREVIOUS ANALYSIS:\n${context.analysis}\n` : ''}
${context.strategy ? `SUGGESTED STRATEGY:\n${context.strategy}\n` : ''}
${context.tradeSetup ? `TRADE SETUP:
- Entry: ${context.tradeSetup.entry}
- Target: ${context.tradeSetup.target}
- Stop Loss: ${context.tradeSetup.stopLoss}
` : ''}

Your role is to:
1. Answer questions about options strike prices, expiration dates, and strategy selection
2. Explain the reasoning behind trading decisions
3. Discuss risk management and position sizing
4. Analyze how recent news or market conditions might affect the trade
5. Compare different options strategies (calls, puts, spreads, etc.)
6. Provide specific, actionable advice based on the current market data

Keep responses concise but informative. Use bullet points when listing multiple items. Always consider risk/reward ratios.`;
}
